# Add type: unittest label if any changes in tests folders
'type: unittest':
- tests/**/*
- tests/**
- openpype/tests/**/*
- openpype/tests/**

# any changes in documentation structure
'type: documentation':
- website/**/*
- website/**
- docs/**/*
- docs/**

# hosts triage
'host: Nuke':
- openpype/hosts/nuke/**/*
- openpype/hosts/nuke/**

'host: Photoshop':
- openpype/hosts/photoshop/**/*
- openpype/hosts/photoshop/**

'host: Harmony':
- openpype/hosts/harmony/**/*
- openpype/hosts/harmony/**

'host: UE':
- openpype/hosts/unreal/**/*
- openpype/hosts/unreal/**

'host: Houdini':
- openpype/hosts/houdini/**/*
- openpype/hosts/houdini/**

'host: Maya':
- openpype/hosts/maya/**/*
- openpype/hosts/maya/**

'host: Resolve':
- openpype/hosts/resolve/**/*
- openpype/hosts/resolve/**

'host: Blender':
- openpype/hosts/blender/**/*
- openpype/hosts/blender/**

'host: Hiero':
- openpype/hosts/hiero/**/*
- openpype/hosts/hiero/**

'host: Fusion':
- openpype/hosts/fusion/**/*
- openpype/hosts/fusion/**

'host: Flame':
- openpype/hosts/flame/**/*
- openpype/hosts/flame/**

'host: TrayPublisher':
- openpype/hosts/traypublisher/**/*
- openpype/hosts/traypublisher/**

'host: 3dsmax':
- openpype/hosts/max/**/*
- openpype/hosts/max/**

'host: TV Paint':
- openpype/hosts/tvpaint/**/*
- openpype/hosts/tvpaint/**

'host: CelAction':
- openpype/hosts/celaction/**/*
- openpype/hosts/celaction/**

'host: After Effects':
- openpype/hosts/aftereffects/**/*
- openpype/hosts/aftereffects/**

'host: Substance Painter':
- openpype/hosts/substancepainter/**/*
- openpype/hosts/substancepainter/**

# modules triage
'module: Deadline':
- openpype/modules/deadline/**/*
- openpype/modules/deadline/**

'module: RoyalRender':
- openpype/modules/royalrender/**/*
- openpype/modules/royalrender/**

'module: Sitesync':
- openpype/modules/sync_server/**/*
- openpype/modules/sync_server/**

'module: Ftrack':
- openpype/modules/ftrack/**/*
- openpype/modules/ftrack/**

'module: Shotgrid':
- openpype/modules/shotgrid/**/*
- openpype/modules/shotgrid/**

'module: Kitsu':
- openpype/modules/kitsu/**/*
- openpype/modules/kitsu/**
