# Add type: unittest label if any changes in tests folders
type: unittest:
- any: ['tests/**/*', 'openpype/tests/**/*']

# any changes in documentation structure
type: documentation:
- any: ['website/**/*', 'docs/**/*']