name: 📇 Code Linting

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

permissions:
  contents: read
  pull-requests: write

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Code Check
        uses: wemake-services/wemake-python-styleguide@master
        with:
          reporter: 'github-pr-review'
        env:
          GITHUB_TOKEN: "${{ secrets.YNPUT_BOT_TOKEN }}"
