name: 📇 Code Linting

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Code Check
      - uses: wemake-services/wemake-python-styleguide@master
        with:
          reporter: 'github-pr-review'
          GITHUB_TOKEN: "${{ secrets.YNPUT_BOT_TOKEN }}"
